@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2NlZTRkMGM3NWYwYTMwNWViNzYyNiIsIm5hbWUiOiJMYWJoYW0gSmFpbiIsImVtYWlsIjoiY29kaW5nLmxhYmhhbUBnbWFpbC5jb20iLCJpYXQiOjE2NTIzNTQ2Mzh9.xWCu6ERkC1GxzKFiUZ-foJpdvc08DvzYDNHxznshWwI

GET {{host}}/video/8723487234876
Content-Type: application/json
